### ISSUE TITLE
Can't import project

### ISSUE THREAD

**Issue by dnezam** [godotengine/godot-benchmarks#5]
Whenever I try to import the project, I get the following error:

> The following project settings file does not specify the version of Godot through which it was created.

After confirming with "ok", it just shows me the project manager again.

The error in cmd:
```
ERROR: _parse: ConfigFile parse error at C:/.../godot-benchmarks-main/project.godot:5: Unexpected character..
   At: core/io/config_file.cpp:296
Editing project: C:/.../godot-benchmarks-main (C:::...::godot-benchmarks-main)
ERROR: _load_settings_text: Error parsing C:/.../godot-benchmarks-main/project.godot at line 5: Unexpected character. File might be corrupted.
   At: core/project_settings.cpp:590
ERROR: _load_settings_text_or_binary: Couldn't load file 'C:/.../godot-benchmarks-main/project.godot', error code 43.
   At: core/project_settings.cpp:630
```

**Comment by Calinou** [comment]
The project is meant to be opened with the `master` branch of Godot, not 3.3.

**Comment by dnezam** [comment]
I see, that makes sense. Thanks!

The project folder isn't placed in a folder named `...`; I just censored the real path due to privacy reasons. Sorry, seems that I forgot to add that.
